### ISSUE TITLE
Any progress with the assembly instructions?

### ISSUE THREAD

**Issue by monkeini** [rkrenicki/Tandy-EX-HX-3in1#1]
I have sourced all parts...would be good to at least have a suggested order of soldering etc. Thanks.

**Comment by rkrenicki** [comment]
There will not be any further documentation created.   The suggested order of assembly is already in the README.md file, all part values are clearly marked on the PCB itself, and there is a pdf detailing how to modify the CF adapter.

I removed the old reference to the instructions in the TODO section of the README, as that was before the abovementioned parts were written.

**Comment by monkeini** [comment]
Okay, thanks. Just assumed more coming given that comment. Fire up the soldering iron!
